# Shared setup logic for isolated per-branch worktrees, used by both the
# manual entry point (scripts/new-worktree.sh) and the WorktreeCreate hook
# (scripts/worktree-create-hook.sh), so native `--worktree`/isolation:"worktree"
# spawns get the exact same Docker/Supabase isolation as manual ones.
#
# Usage: source this file, then call setup_worktree "$BRANCH" "$TARGET"
# Requires: ROOT and WORKTREES_DIR set by the caller.

# Idempotent: safe to call again for a branch/dir that already exists (the
# WorktreeCreate hook must not fail on retry/collision — any non-zero exit
# fails the whole worktree creation).
setup_worktree() {
  local BRANCH="$1"
  local TARGET="$2"
  local SLUG
  SLUG="$(basename "$TARGET")"

  mkdir -p "$WORKTREES_DIR"

  # Already fully set up (e.g. re-entrant hook call) — just confirm and return.
  if [ -f "$TARGET/.env" ] && grep -q '^COMPOSE_PROJECT_NAME=' "$TARGET/.env"; then
    return 0
  fi

  # Offset allocation races when multiple agents create worktrees concurrently:
  # serialize the scan-and-claim with a simple mkdir lock (atomic on POSIX and
  # NTFS via Git Bash).
  local LOCK="$WORKTREES_DIR/.offset.lock"
  local tries=0
  until mkdir "$LOCK" 2>/dev/null; do
    tries=$((tries + 1))
    [ "$tries" -gt 100 ] && { echo "error: timed out waiting for worktree offset lock" >&2; return 1; }
    sleep 0.1
  done
  trap 'rmdir "'"$LOCK"'" 2>/dev/null || true' RETURN

  local OFFSET=1
  for f in "$WORKTREES_DIR"/*/.env; do
    [ -f "$f" ] || continue
    used=$(sed -n 's/^WORKTREE_OFFSET=//p' "$f")
    [ -n "$used" ] && [ "$used" -ge "$OFFSET" ] && OFFSET=$((used + 1))
  done

  local APP_PORT=$((3000 + OFFSET))
  local DB_PORT=$((54322 + OFFSET * 10))
  local API_PORT=$((54321 + OFFSET * 10))
  local SHADOW_PORT=$((54320 + OFFSET * 10))
  local POOLER_PORT=$((54329 + OFFSET * 10))
  local STUDIO_PORT=$((54323 + OFFSET * 10))
  local SMTP_PORT=$((54324 + OFFSET * 10))
  local ANALYTICS_PORT=$((54327 + OFFSET * 10))
  local INSPECTOR_PORT=$((8083 + OFFSET))
  local PROJECT_NAME="hub-$SLUG"
  local SUPABASE_PROJECT_ID="hub-$SLUG"

  # Reuse-or-create: a hook retry, or a branch another process already made,
  # must not turn into a hard failure.
  if [ ! -e "$TARGET" ]; then
    if git -C "$ROOT" rev-parse --verify "$BRANCH" >/dev/null 2>&1; then
      git -C "$ROOT" worktree add "$TARGET" "$BRANCH"
    else
      git -C "$ROOT" worktree add "$TARGET" -b "$BRANCH"
    fi
  fi

  cat >"$TARGET/.env" <<EOF
# Generated by scripts/new-worktree.sh — keeps this worktree's Docker/Supabase
# stack isolated from other worktrees running at the same time. Google OAuth
# secrets (see docs/setup/google-oauth.md) can be appended to this same file.
WORKTREE_OFFSET=$OFFSET
COMPOSE_PROJECT_NAME=$PROJECT_NAME
APP_PORT=$APP_PORT
SUPABASE_DB_PORT=$DB_PORT
SUPABASE_API_PORT=$API_PORT
SUPABASE_STUDIO_PORT=$STUDIO_PORT
EOF

  # Release the offset lock now — the rest of setup (port rewrites, env copy,
  # docker up) doesn't touch shared state and shouldn't hold up other agents.
  rmdir "$LOCK" 2>/dev/null || true
  trap - RETURN

  # supabase/config.toml has no env-var indirection for ports, so rewrite the
  # copy in this worktree directly. skip-worktree hides the diff from `git
  # status` in this worktree so it's never accidentally committed.
  local CFG="$TARGET/supabase/config.toml"
  sed -i.bak \
    -e "s/^project_id = \".*\"/project_id = \"$SUPABASE_PROJECT_ID\"/" \
    -e "0,/^port = 54321\$/s//port = $API_PORT/" \
    -e "0,/^port = 54322\$/s//port = $DB_PORT/" \
    -e "0,/^shadow_port = 54320\$/s//shadow_port = $SHADOW_PORT/" \
    -e "0,/^port = 54329\$/s//port = $POOLER_PORT/" \
    -e "0,/^port = 54323\$/s//port = $STUDIO_PORT/" \
    -e "0,/^port = 54324\$/s//port = $SMTP_PORT/" \
    -e "0,/^port = 54327\$/s//port = $ANALYTICS_PORT/" \
    -e "0,/^inspector_port = 8083\$/s//inspector_port = $INSPECTOR_PORT/" \
    -e "s#^site_url = \"http://localhost:3000\"#site_url = \"http://localhost:$APP_PORT\"#" \
    -e "s#^additional_redirect_urls = \\[\"http://localhost:3000/auth/callback\"\\]#additional_redirect_urls = [\"http://localhost:$APP_PORT/auth/callback\"]#" \
    -e "s#^redirect_uri = \"http://127.0.0.1:54321/auth/v1/callback\"#redirect_uri = \"http://127.0.0.1:$API_PORT/auth/v1/callback\"#" \
    "$CFG"
  rm -f "$CFG.bak"
  git -C "$TARGET" update-index --skip-worktree supabase/config.toml

  # .env.local is gitignored (never committed) but next dev/dev-up.sh needs it to
  # even boot — without it the app 500s on every request (server can't resolve a
  # Supabase URL). Derive this worktree's copy from the main checkout's, if
  # present, swapping in this worktree's ports. The anon/service-role keys are
  # stable demo JWTs baked into every local Supabase instance, so only the ports
  # differ between worktrees.
  local MAIN_ENV_LOCAL="$ROOT/.env.local"
  if [ -f "$MAIN_ENV_LOCAL" ]; then
    sed \
      -e "s#://127\\.0\\.0\\.1:54321#://127.0.0.1:$API_PORT#g" \
      -e "s#://host\\.docker\\.internal:54321#://host.docker.internal:$API_PORT#g" \
      "$MAIN_ENV_LOCAL" >"$TARGET/.env.local"
    # Give this worktree its own session-signing secret rather than reusing the
    # main checkout's.
    if grep -q '^STUDENT_SESSION_SECRET=' "$TARGET/.env.local"; then
      sed -i.bak "s#^STUDENT_SESSION_SECRET=.*#STUDENT_SESSION_SECRET=$(openssl rand -hex 32)#" "$TARGET/.env.local"
      rm -f "$TARGET/.env.local.bak"
    fi
  else
    echo "warning: no .env.local in $ROOT — copy .env.example to $TARGET/.env.local and fill it in, or the app won't boot" >&2
  fi

  echo "Worktree ready: $TARGET"
  echo "  App:              http://localhost:$APP_PORT"
  echo "  Supabase Studio:  http://localhost:$STUDIO_PORT"
  echo "  Supabase API:     http://localhost:$API_PORT"

  # Bring the isolated stack up in the background so it's ready by the time
  # anything looks for it (e.g. the SessionStart hook). Non-fatal if it fails —
  # `./dev` / `docker compose up` still work from the worktree directly.
  if [ "${NEW_WORKTREE_SKIP_UP:-}" != "1" ]; then
    echo "Starting isolated stack '$PROJECT_NAME' in the background…"
    ( cd "$TARGET" && docker compose up -d >"/tmp/compose-up-$PROJECT_NAME.log" 2>&1 & ) || true
  fi
}
