#!/usr/bin/env bash
# Spin up an isolated git worktree with its own Docker Compose stack and local
# Supabase instance, so several branches can run side by side (each `./dev up`
# gets its own containers, network, and ports — no collisions).
#
#   scripts/new-worktree.sh <branch-name>
#
# Then, from the new worktree directory:
#   ./dev            # or: docker compose up
set -euo pipefail

BRANCH="${1:?usage: scripts/new-worktree.sh <branch-name>}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WORKTREES_DIR="$ROOT/.claude/worktrees"
TARGET="$WORKTREES_DIR/$BRANCH"

if [ -e "$TARGET" ]; then
  echo "error: $TARGET already exists" >&2
  exit 1
fi

# Next free offset: count existing worktrees that already claimed one.
# Each offset shifts every port by 10, well clear of Supabase's own port block.
OFFSET=1
for f in "$WORKTREES_DIR"/*/.env; do
  [ -f "$f" ] || continue
  used=$(sed -n 's/^WORKTREE_OFFSET=//p' "$f")
  [ -n "$used" ] && [ "$used" -ge "$OFFSET" ] && OFFSET=$((used + 1))
done

APP_PORT=$((3000 + OFFSET))
DB_PORT=$((54322 + OFFSET * 10))
API_PORT=$((54321 + OFFSET * 10))
SHADOW_PORT=$((54320 + OFFSET * 10))
POOLER_PORT=$((54329 + OFFSET * 10))
STUDIO_PORT=$((54323 + OFFSET * 10))
SMTP_PORT=$((54324 + OFFSET * 10))
ANALYTICS_PORT=$((54327 + OFFSET * 10))
INSPECTOR_PORT=$((8083 + OFFSET))
PROJECT_NAME="hub-$BRANCH"
SUPABASE_PROJECT_ID="hub-$BRANCH"

git -C "$ROOT" worktree add "$TARGET" -b "$BRANCH"

# Written to .env (not .env.worktree) so `docker compose` auto-loads it for
# variable substitution — that's the file Compose reads by convention.
cat >"$TARGET/.env" <<EOF
# Generated by scripts/new-worktree.sh — keeps this worktree's Docker/Supabase
# stack isolated from other worktrees running at the same time. Google OAuth
# secrets (see docs/setup/google-oauth.md) can be appended to this same file.
WORKTREE_OFFSET=$OFFSET
COMPOSE_PROJECT_NAME=$PROJECT_NAME
APP_PORT=$APP_PORT
SUPABASE_DB_PORT=$DB_PORT
EOF

# supabase/config.toml has no env-var indirection for ports, so rewrite the
# copy in this worktree directly. skip-worktree hides the diff from `git
# status` in this worktree so it's never accidentally committed.
CFG="$TARGET/supabase/config.toml"
sed -i \
  -e "s/^project_id = \".*\"/project_id = \"$SUPABASE_PROJECT_ID\"/" \
  -e "0,/^port = 54321\$/s//port = $API_PORT/" \
  -e "0,/^port = 54322\$/s//port = $DB_PORT/" \
  -e "0,/^shadow_port = 54320\$/s//shadow_port = $SHADOW_PORT/" \
  -e "0,/^port = 54329\$/s//port = $POOLER_PORT/" \
  -e "0,/^port = 54323\$/s//port = $STUDIO_PORT/" \
  -e "0,/^port = 54324\$/s//port = $SMTP_PORT/" \
  -e "0,/^port = 54327\$/s//port = $ANALYTICS_PORT/" \
  -e "0,/^inspector_port = 8083\$/s//inspector_port = $INSPECTOR_PORT/" \
  "$CFG"
git -C "$TARGET" update-index --skip-worktree supabase/config.toml

echo "Worktree ready: $TARGET"
echo "  App:              http://localhost:$APP_PORT"
echo "  Supabase Studio:  http://localhost:$STUDIO_PORT"
echo "  Supabase API:     http://localhost:$API_PORT"
echo
echo "cd \"$TARGET\" && ./dev"
