#!/usr/bin/env bash
# Spin up an isolated git worktree with its own Docker Compose stack and local
# Supabase instance, so several branches can run side by side (each `./dev up`
# gets its own containers, network, and ports — no collisions).
#
#   scripts/new-worktree.sh <branch-name>
#
# Then, from the new worktree directory:
#   ./dev            # or: docker compose up
set -euo pipefail

BRANCH="${1:?usage: scripts/new-worktree.sh <branch-name>}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WORKTREES_DIR="$ROOT/.claude/worktrees"
# Branch names often contain "/" (e.g. "feat/foo"); git is fine with that, but
# it would otherwise create nested directories under WORKTREES_DIR, breaking
# the offset scan below. Keep the on-disk dir a flat slug; the branch itself
# still gets the name as given.
SLUG="${BRANCH//\//-}"
TARGET="$WORKTREES_DIR/$SLUG"

if [ -e "$TARGET" ]; then
  echo "error: $TARGET already exists" >&2
  exit 1
fi

mkdir -p "$WORKTREES_DIR"

# Next free offset: count existing worktrees that already claimed one.
# Each offset shifts every port by 10, well clear of Supabase's own port block.
OFFSET=1
for f in "$WORKTREES_DIR"/*/.env; do
  [ -f "$f" ] || continue
  used=$(sed -n 's/^WORKTREE_OFFSET=//p' "$f")
  [ -n "$used" ] && [ "$used" -ge "$OFFSET" ] && OFFSET=$((used + 1))
done

APP_PORT=$((3000 + OFFSET))
DB_PORT=$((54322 + OFFSET * 10))
API_PORT=$((54321 + OFFSET * 10))
SHADOW_PORT=$((54320 + OFFSET * 10))
POOLER_PORT=$((54329 + OFFSET * 10))
STUDIO_PORT=$((54323 + OFFSET * 10))
SMTP_PORT=$((54324 + OFFSET * 10))
ANALYTICS_PORT=$((54327 + OFFSET * 10))
INSPECTOR_PORT=$((8083 + OFFSET))
PROJECT_NAME="hub-$SLUG"
SUPABASE_PROJECT_ID="hub-$SLUG"

git -C "$ROOT" worktree add "$TARGET" -b "$BRANCH"

# Written to .env (not .env.worktree) so `docker compose` auto-loads it for
# variable substitution — that's the file Compose reads by convention.
cat >"$TARGET/.env" <<EOF
# Generated by scripts/new-worktree.sh — keeps this worktree's Docker/Supabase
# stack isolated from other worktrees running at the same time. Google OAuth
# secrets (see docs/setup/google-oauth.md) can be appended to this same file.
WORKTREE_OFFSET=$OFFSET
COMPOSE_PROJECT_NAME=$PROJECT_NAME
APP_PORT=$APP_PORT
SUPABASE_DB_PORT=$DB_PORT
SUPABASE_API_PORT=$API_PORT
SUPABASE_STUDIO_PORT=$STUDIO_PORT
EOF

# supabase/config.toml has no env-var indirection for ports, so rewrite the
# copy in this worktree directly. skip-worktree hides the diff from `git
# status` in this worktree so it's never accidentally committed.
CFG="$TARGET/supabase/config.toml"
# `-i.bak` (with suffix, no space) is the one form both GNU and BSD/macOS sed
# accept; drop the backup right after.
sed -i.bak \
  -e "s/^project_id = \".*\"/project_id = \"$SUPABASE_PROJECT_ID\"/" \
  -e "0,/^port = 54321\$/s//port = $API_PORT/" \
  -e "0,/^port = 54322\$/s//port = $DB_PORT/" \
  -e "0,/^shadow_port = 54320\$/s//shadow_port = $SHADOW_PORT/" \
  -e "0,/^port = 54329\$/s//port = $POOLER_PORT/" \
  -e "0,/^port = 54323\$/s//port = $STUDIO_PORT/" \
  -e "0,/^port = 54324\$/s//port = $SMTP_PORT/" \
  -e "0,/^port = 54327\$/s//port = $ANALYTICS_PORT/" \
  -e "0,/^inspector_port = 8083\$/s//inspector_port = $INSPECTOR_PORT/" \
  -e "s#^site_url = \"http://localhost:3000\"#site_url = \"http://localhost:$APP_PORT\"#" \
  -e "s#^additional_redirect_urls = \\[\"http://localhost:3000/auth/callback\"\\]#additional_redirect_urls = [\"http://localhost:$APP_PORT/auth/callback\"]#" \
  -e "s#^redirect_uri = \"http://127.0.0.1:54321/auth/v1/callback\"#redirect_uri = \"http://127.0.0.1:$API_PORT/auth/v1/callback\"#" \
  "$CFG"
rm -f "$CFG.bak"
git -C "$TARGET" update-index --skip-worktree supabase/config.toml

# .env.local is gitignored (never committed) but next dev/dev-up.sh needs it to
# even boot — without it the app 500s on every request (server can't resolve a
# Supabase URL). Derive this worktree's copy from the main checkout's, if
# present, swapping in this worktree's ports. The anon/service-role keys are
# stable demo JWTs baked into every local Supabase instance, so only the ports
# differ between worktrees.
MAIN_ENV_LOCAL="$ROOT/.env.local"
if [ -f "$MAIN_ENV_LOCAL" ]; then
  sed \
    -e "s#://127\\.0\\.0\\.1:54321#://127.0.0.1:$API_PORT#g" \
    -e "s#://host\\.docker\\.internal:54321#://host.docker.internal:$API_PORT#g" \
    "$MAIN_ENV_LOCAL" >"$TARGET/.env.local"
  # Give this worktree its own session-signing secret rather than reusing the
  # main checkout's.
  if grep -q '^STUDENT_SESSION_SECRET=' "$TARGET/.env.local"; then
    sed -i.bak "s#^STUDENT_SESSION_SECRET=.*#STUDENT_SESSION_SECRET=$(openssl rand -hex 32)#" "$TARGET/.env.local"
    rm -f "$TARGET/.env.local.bak"
  fi
else
  echo "warning: no .env.local in $ROOT — copy .env.example to $TARGET/.env.local and fill it in, or the app won't boot" >&2
fi

echo "Worktree ready: $TARGET"
echo "  App:              http://localhost:$APP_PORT"
echo "  Supabase Studio:  http://localhost:$STUDIO_PORT"
echo "  Supabase API:     http://localhost:$API_PORT"

# Bring the isolated stack up in the background so it's ready by the time
# anything looks for it (e.g. the SessionStart hook). Non-fatal if it fails —
# `./dev` / `docker compose up` still work from the worktree directly.
if [ "${NEW_WORKTREE_SKIP_UP:-}" != "1" ]; then
  echo "Starting isolated stack '$PROJECT_NAME' in the background…"
  ( cd "$TARGET" && docker compose up -d >"/tmp/compose-up-$PROJECT_NAME.log" 2>&1 & ) || true
fi

echo
echo "cd \"$TARGET\" && ./dev"
